// Copyright 2025 Your Name (@tstrube)
// SPDX-License-Identifier: GPL-2.0-or-later
#pragma once

#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 200U

#define SPLIT_TRANSACTION_IDS_USER RPC_JOYSTICK_AXES, RPC_USER_CONFIG